# fly.toml app configuration file generated for reactdotnetstore on 2024-08-04T12:33:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactdotnetstore'
primary_region = 'mia'

[build]
  image = 'wdiazdev/reactdotnetstore:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51PhGKxDFOlsEJFO7FS3ka6HrksbbDHcQ5rqlKBu1zUMXscHxKNuPKUBkiWh410HNSh2H35qHLySy9OG5gCe9Y9Az004S56frKF"
  Cloudinary__CloudName="dxrtbjypv"
  Cloudinary__ApiKey="317527291813943"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
